version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    volumes:
      - ./config/livekit.yaml:/etc/livekit.yaml
    ports:
      - "7880:7880" # HTTP API
      - "7881:7881" 
      - "51000-51010:51000-51010/udp" # WebRTC UDP
    environment:
      - LIVEKIT_REDIS_HOST=redis
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret

  livekit-ingress:
    image: livekit/ingress:latest
    restart: always
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # WHIP
    depends_on:
      - livekit
    environment:
      - INGRESS_CONFIG_FILE=/ingress.yaml
    volumes:
      - ./config/ingress.yaml:/ingress.yaml


  ffmpeg-streamer:
    image: jrottenberg/ffmpeg:6.0-ubuntu2204
    volumes:
      - ./videos:/videos
    depends_on:
      - livekit-ingress
    entrypoint: >
      ffmpeg -re -stream_loop -1 -i /videos/8.mp4
             -vf "scale=1280:720"
             -pix_fmt yuv420p -r 25 -g 50 -keyint_min 50 -sc_threshold 0
             -c:v libx264 -preset veryfast -tune zerolatency -bf 0
             -c:a aac -b:a 128k
             -f flv rtmp://livekit-ingress:1935/live/BG2tGvA3mm58


