### 建立一個新的 RTMP Ingress
POST http://localhost:7880/twirp/livekit.Ingress/CreateIngress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQ3JlYXRlIjp0cnVlLCJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6InRlc3Qtcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZSwiY2FuUHVibGlzaERhdGEiOnRydWUsImluZ3Jlc3NBZG1pbiI6dHJ1ZX0sInN1YiI6ImFkbWluLWNsaWVudCIsImlzcyI6ImRldmtleSIsIm5iZiI6MTc1Mzg3MDUzOCwiZXhwIjoxNzUzOTA2NTM4fQ.4WqMaze6l_UD9HvbU9DEqTI-w3NTeOSPGkoLEjTX7M8
Content-Type: application/json

{
  "input_type": "RTMP_INPUT",
  "name": "My Ingress",
  "room_name": "test-room",
  "participant_identity": "camera01"
}

### 建立一個新的 WHIP Ingress
POST http://localhost:7880/twirp/livekit.Ingress/CreateIngress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQ3JlYXRlIjp0cnVlLCJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6InRlc3Qtcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZSwiY2FuUHVibGlzaERhdGEiOnRydWUsImluZ3Jlc3NBZG1pbiI6dHJ1ZX0sInN1YiI6ImFkbWluLWNsaWVudCIsImlzcyI6ImRldmtleSIsIm5iZiI6MTc1Mzg3MDUzOCwiZXhwIjoxNzUzOTA2NTM4fQ.4WqMaze6l_UD9HvbU9DEqTI-w3NTeOSPGkoLEjTX7M8
Content-Type: application/json

{
  "input_type": "WHIP_INPUT",
  "name": "My Ingress",
  "room_name": "test-room",
  "participant_identity": "camera02"
}

### 列出所有 Ingress
POST http://localhost:7880/twirp/livekit.Ingress/ListIngress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQ3JlYXRlIjp0cnVlLCJyb29tSm9pbiI6dHJ1ZSwicm9vbSI6InRlc3Qtcm9vbSIsImNhblB1Ymxpc2giOnRydWUsImNhblN1YnNjcmliZSI6dHJ1ZSwiY2FuUHVibGlzaERhdGEiOnRydWUsImluZ3Jlc3NBZG1pbiI6dHJ1ZX0sInN1YiI6ImFkbWluLWNsaWVudCIsImlzcyI6ImRldmtleSIsIm5iZiI6MTc1Mzg3MDUzOCwiZXhwIjoxNzUzOTA2NTM4fQ.4WqMaze6l_UD9HvbU9DEqTI-w3NTeOSPGkoLEjTX7M8
Content-Type: application/json

{
  "room_name": "" 
}