port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 45100
    port_range_end: 50000
    use_external_ip: true
    stun_servers:
      # - stun:turn.tnebp.furthersoftware.com.tw:3478
      # - turn.tnebp.furthersoftware.com.tw:3478
    turn_servers:
      - host: turn.tnebp.furthersoftware.com.tw
        port: 5349
        protocol: tls
        username: coturn
        credential: fs@073807983
    enable_loopback_candidate: true
redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
# turn:
#   enabled: false

# turn:
#   enabled: true
#   domain: turn.tnebp.furthersoftware.com.tw
#   tls_port: 5349
#   udp_port: 3478
#   external_tls: false

ingress:
  rtmp_base_url: rtmp://ingress.tnebp.furthersoftware.com.tw/live
  # whip_base_url: http://localhost:8080/whip
  whip_base_url: https://ingress.tnebp.furthersoftware.com.tw/whip

keys:
  devkey: k7sd8fh2jf9832j2sdf8sdhkj23jk2jkf93hkj2kjsdf

